### ISSUE TITLE
Beta is broken with wayland

### ISSUE THREAD

**Issue by hfiguiere** [flathub/com.github._4lex4.ScanTailor-Advanced#5]
With waylang the main view (the one that display the page) is broken, ie it display nothing, or whatever was in that screen rectangle if you switch active window / app back and forth. Disabling wayland with `--nosocket=wayland` works by falling back Xwayland.

I run Mutter with GNOME 42. Also happened with older GNOME.

**Comment by Unrud** [comment]
I can't reproduce the problem. I've tested with Intel and Nvidia (Optimus) graphics on Gnome 42.1 (Fedora Silverblue).

**Comment by hfiguiere** [comment]
I use 
```
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
```

Fedora Silverblue 36, GNOME w/ wayland
I remember it happening down to Fedora 33 (still the same hardware)

**Comment by hfiguiere** [comment]
My experience is that Qt isn't reliable with Wayland. And upstream disable Wayland when run in a GNOME session but this is disabled with the flatpak runtime.
